### ISSUE TITLE
Incorrect q_in_cryst_coord = .false. for `matdyn.x`` input in Hands-on Phonon dispersion?

### ISSUE THREAD

**Issue by Tosykie** [pranabdas/espresso#33]
Hi Dr Pranab K. Das,

I found that the input file of `src/GaAs-phonon/matdyn.GaAs.in` for obtaining the phonon dispersion has a default parameter of .false. for q_in_cryst_coord. This means that by default the specified q-points are given with Cartesian coordinates in units of $2\pi/a, 2\pi/b, 2\pi/c$ but **NOT** in the in crystal coordinates (relative coordinates of the reciprocal lattice vectors which is the general, or say, convinient form for high-symmetry k-point path).

The probable incorrect combinations of `q_in_cryst_coord = .false.` with the listed q-point lines
```fortan
5
0.500 0.500 0.500   20 ! L
0.000 0.000 0.000   20 ! G
0.500 0.000 0.500   20 ! X
0.375 0.375 0.750   20 ! K
0.000 0.000 0.000    1 ! G
```
may lead to wrong phonon modes at non-$\Gamma$ point.

As we might see from the example output that the **unusual** connections near the X point and incorrect degeneracy for the two transverse acoustic modes along $\Gamma$ to X. 
![phonon_GaAs](https://github.com/pranabdas/espresso/blob/main/static/img/GaAs-phonon.png)

We could find from many DFT studies as well as the experimental measurements that the two transverse acoustic modes should be degenerate for both along the paths $\Gamma$ to X and $\Gamma$ to L, while they are splitted along $\Gamma$ to K.

I suggest adding the `q_in_cryst_coord = .true.` in `src/GaAs-phonon/matdyn.GaAs.in` file and update the phonon dispersion of GaAs in the Hand-on tutorial so that the reader could not be misled.

Hope this helps.

Best,
Nong Wei
PhD Candidate, Nanyang Technological University, Singapore

**Comment by pranabdas** [comment]
Dear Nong Wei, thank you very much for reporting the issue in detail. You are right about the default value of `q_in_cryst_coord` parameter. I have also noticed the discrepancy in the dispersion features. Let me repeat the calculation and update in - https://github.com/pranabdas/espresso/pull/34

**Comment by pranabdas** [comment]
@Tosykie I have updated the tutorial, please let me know if you see any other issues. Thank you very much.
